### ISSUE TITLE
Add user details page/popup

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#169]
A department admin should be able to view a users username and possibly other attributes not currently seen in the table. 

What do you think of a popup or another page for user details?

**Comment by larskendall** [comment]
@chopchop505 On normal screen widths it doesn't seem to be a problem including the username in the table. It only becomes an issue below about 1300px. I was making the page switch to the mobile view at 1200px, but I think I'll just bump that up to 1300px. Unless we need to include more user info, I think that will get the job done fine. The only (slight) drawback is that between 1200px and 1300px screen width most tables will show regularly but that page will show as cards. I don't think anyone without OCD will care though.

**Comment by larskendall** [comment]
If we do need to include more user info, I think we'd probably be best off going with a solution like using DataTables (https://datatables.net/), where each row can be expanded to show more info. But I'd say we should wait on that as long as possible since it may require a day or so of extra programming and styling to integrate.
