### ISSUE TITLE
As a user, I should be able to print incident analysis pages

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#273]
Multiple users have requested the ability to download/print the incident analysis reports.

- Export to pdf using phantom js or similar?
- Print in chrome?

The solution should be reusable for unit analysis pages.

**Comment by larskendall** [comment]
After reading a little bit about this, it looks like defining custom css to make the page print cleanly is going to be fairly straightforward. I just tried tweaking one rule and it already looks pretty good. The only slightly tricky part will be setting page breaks at the right spots, so that UI components don't get split between two pages. But apparently there are CSS rules for placing those.

So I'm thinking we should just go the CSS route, adding a print button somewhere in the UI. Users can always print to PDF if they want to save it out that way. Do you think that's a reasonable approach?
